# Generated by Django 4.1.2 on 2022-10-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('exp_month', models.CharField(max_length=100)),
                ('exp_year', models.CharField(max_length=100)),
                ('cvc', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=20)),
                ('plan_price', models.CharField(choices=[('100', '100'), ('1200', '1200')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_api.subscriptionplan')),
            ],
        ),
    ]
